### ISSUE TITLE
about the viewer

### ISSUE THREAD

**Issue by jianjun0407** [alibaba-damo-academy/ct-sam3d#2]
First of all, thank you for sharing the code and models !
I installed the corresponding dependencies as you suggested，There was an error in executing the show() function in visualization.py:
![3](https://github.com/user-attachments/assets/bb6f770a-5c5e-4caf-a495-2e264871390d)

![1](https://github.com/user-attachments/assets/d80e3c4e-6aad-4199-a956-df3b2d6bb9c1)

I find that the problem is self.server=None，
![2](https://github.com/user-attachments/assets/977ce82b-6763-4df8-9a84-871b8b3e255d)
My current version of the related library is as follows:
numpy=1.22.4
itkwidgets=1.0a49
I suspect this problem is a library version issue, do you have any suggestions？

**Comment by henguo** [comment]
Hi, Jianjun,

You may troubleshoot this issue through two steps:
1) Check whether the imjoy-jupyterlab-extension has been installed successfully. The ImJoy logo should present as:
![image](https://github.com/user-attachments/assets/702dcf20-94ba-448d-8be7-62f7a000ab8a)

2) Install the customized itkwidgets from https://github.com/henguo/itkwidgets.git, when this is installed, the version of itkwidgets should not be 1.0a49.

**Comment by jianjun0407** [comment]
Thank you for your advice, I give it a try~

**Comment by jianjun0407** [comment]
First of all, I installed the official version of itkwidgets (https://github.com/InsightSoftwareConsortium/itkwidgets), "visualization.ipynb" of CT-SAM3D can run.
However, there is an error: "Viewer" object has no attribute "points". I assume that the official version of itkwidgets library does not support such interaction as adding points. I need to install the custom version of itkwidgets library as you suggested, My installation method is : "pip install git+https://github.com/henguo/itkwidgets.git"


![4](https://github.com/user-attachments/assets/bf670f5d-46e0-4a7f-953f-3302991e9cc7)


Now, I have two questions:
First, with this customized version of the itkwidgets library, the image display interface is gone
![5](https://github.com/user-attachments/assets/27d2af4e-89b1-4a4c-b118-f7b793e92ae4)


Second, the implementation of "pip install numpy = = 1.22.4",  some  library version are not compatible, such as: scipy, zarr, matplotlib, etc. Do you have to use numpy version 1.22.4?

![6](https://github.com/user-attachments/assets/521e6f6f-c2ae-4301-ba85-9946001ec810)

**Comment by henguo** [comment]
The first issue is that the imjoy-jupyterlab-extension is not activated, as evidenced by the absence of the ImJoy logo in the toolbar. After installing the customized itkwidgets, the imjoy-jupyterlab-extension should still be activated.

The second issue can be resolved by installing a compatible version of numpy in your runtime environment. Version 1.22.4 works for us, but we have not tested other versions.
